input = {
    KEY_A |
    KEY_B |
    KEY_X |
    KEY_Y |
    KEY_Dl |
    KEY_Du |
    KEY_Dr |
    KEY_Dd 
}
    KEY_A = { "A" }
    KEY_B = { "B" }
    KEY_X = { "X" }
    KEY_Y = { "Y" }
    KEY_Dl = { "Dl" }
    KEY_Du = { "Du" }
    KEY_Dr = { "Dr" }
    KEY_Dd = { "Dd" }
    
frame_number = { ASCII_DIGIT+ }

frame_argument = { "(" ~ frame_number ~ ")" }

full_input = { input ~ frame_argument ~ "\n" }

file = { SOI ~ full_input+ ~ EOI}